package com.carro.washcar.enums;

public enum ServiceType {

    COMMERCIAL_POLISHING,
    COMPLETE_WASH,
    CRYSTAL_POLISHING,
    ENGINE_WASH,
    EXTRA_PAINT_PROTECTION,
    HEADLIGHT_POLISHING,
    INTERNAL_CLEANING,
    INTERNAL_SANITATION,
    MIRROR_POLISHING,
    PAINTING,
    PREMIUM_CHASSIS_PROTECTION,
    PREMIUM_PAINT_PROTECTION,
    SEAT_CLEANING,
    SEAT_SANITATION,
    SIMPLE_WASH,
    TOTAL_WASH,

}
